language: python

compiler:
  - gcc
  - clang

matrix:
  allow_failures:
    - os: osx
  include:
    #- os: linux
    #  dist: xenial
    #  python: 3.5
    - os: linux
      dist: xenial
      python: 3.6
    - os: linux
      dist: xenial
      python: 3.7
    - os: osx
      env: TRAVIS_PYTHON_VERSION=3.7

before_install:
  - |
    if [[ $TRAVIS_OS_NAME == 'osx' ]]; then \
      brew install python${TRAVIS_PYTHON_VERSION}; \
      virtualenv venv -p python3; \
      source venv/bin/activate; \
    fi
  - sudo apt-get install -y lsb-release
  - |
    sudo apt-key adv \
    --keyserver keyserver.ubuntu.com \
    --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9
  - |
    sudo add-apt-repository \
    --yes \
    "deb https://cloud.r-project.org/bin/linux/ubuntu/ $(lsb_release -c -s)-cran35/"
  - cat /etc/apt/sources.list
  - sudo apt-get update -qq
  - sudo apt-get install -y r-base
  - pip install flake8 pytest pytest-cov
  - pip install ipython pandas numpy tzlocal

addons:
  apt:
    update: true

install:
  - python setup.py install

# command to run tests
script:
  - flake8 rpy/rinterface.py rpy/rinterface_lib/
  - |
    pytest \
    --cov=rpy2.rinterface_lib \
    --cov=rpy2.rinterface \
    --cov=rpy2.ipython \
    --cov=rpy2.robjects \
    tests

after_success:
    codecov
