# This is a sample build configuration for Python.
# Check our guides at https://confluence.atlassian.com/x/VYk8Lw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: ubuntu:18.04

pipelines:
  default:
    - step:
        script:
          - >
            apt-get update -qq &&
            DEBIAN_FRONTEND=noninteractive apt-get install -y
            apt-utils
            apt-transport-https
            dirmngr
            gnupg
            libcurl4-openssl-dev
            libnlopt-dev
            lsb-release
          - >
            echo "deb ${CRAN_MIRROR}/bin/linux/ubuntu $(lsb_release -c -s)${CRAN_MIRROR_TAG}/" >>
            /etc/apt/sources.list.d/added_repos.list &&
            apt-key adv --no-tty --keyserver keyserver.ubuntu.com --recv-keys E084DAB9
          - >
            apt-get update -qq &&
            DEBIAN_FRONTEND=noninteractive apt-get install -y
            aptdaemon
            ed
            libcairo-dev
            libedit-dev
            libxml2-dev
            python3
            python3-pip
            python3-venv
            r-base
            r-base-dev
            wget &&
            rm -rf /var/lib/apt/lists/*
          - python3 -m venv py3_env && source py3_env/bin/activate
          - python3 -m pip install --upgrade pip
          - python3 -m pip install numpy pandas ipython
          - python3 setup.py install
          - >
            pytest --junitxml=./test-reports/junit.xml tests/
